-- payment-service schema. Matches com.ecommerce.paymentservice.entity.Payment.
CREATE TABLE payments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL,
    amount_cents BIGINT NOT NULL,
    status       VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
